### PR TITLE
stateTx bor txlookup fix

### LINKED ISSUE #13758: uint underflow txnums error on call to eth_getTransactionReceipt for matic txs
#### System information

Erigon version: `./erigon --version`

erigon:v3.0.0-beta1

Chain/Network:  Matic

#### Actual behaviour

```
curl -X POST http://matic-erigon-node.k8s.local -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x837184c3244be9b14dae022e485e88cf82b411f8b5d2f82e7d4e36eb3c30a3e9"],"id":3617635}'
{"jsonrpc":"2.0","id":3617635,"error":{"code":-32000,"message":"uint underflow txnums error txNum: 0, txNumMin: 5031504367, blockNum: 67765264"}}
```
returns 
```
{"jsonrpc":"2.0","id":3617635,"error":{"code":-32000,"message":"uint underflow txnums error txNum: 0, txNumMin: 5031504367, blockNum: 67765264"}}
```

### PR DESCRIPTION
**Pull request by JkLondon**
closes #13758

### CODE REVIEW

File: eth/stagedsync/stage_txlookup.go [hunk 1]
```diff
@@ -174,15 +173,22 @@ func txnLookupTransform(logPrefix string, tx kv.RwTx, blockFrom, blockTo uint64,
 
 // txnLookupTransform - [startKey, endKey)
 func borTxnLookupTransform(logPrefix string, tx kv.RwTx, blockFrom, blockTo uint64, quitCh <-chan struct{}, cfg TxLookupCfg, logger log.Logger) error {
-	bigNum := new(big.Int)
+	data := make([]byte, 16)
```
Comment (taratorio) [inline eth/stagedsync/stage_txlookup.go:176]: I suspect this won't fix the issue. We now use Astrid and `borTxnLookupTransform` is actually something that is not used/need. It is pending removal - see https://github.com/erigontech/erigon/issues/11678.

With Astrid, the `BorTxLookup` table is updated by the `bridge.Service` at `polygon/bridge/ service.go`. That's why we have a `bridgeReader` in rpcdaemon.

**Review by shohamc1 — APPROVED** [review]
