### PR TITLE
Fixed DDOS on AggregateAndProof

### LINKED ISSUE #11994: High CPU usage on e3 sepolia
Not sure if this is a false positive or a regression, but I didn't notice it before.

Around ~after alpha 3, I've been noticing a constant CPU usage, noticeable both by htop and CPU fans constantly spinning.

Linux machine, debian bookworm.

I'm uploading a 30s pprof output.

[trace.out.gz](https://github.com/user-attachments/files/17000412/trace.out.gz)

### PR DESCRIPTION
**Pull request by Giulio2002**
fixes #11994

### CODE REVIEW

File: cl/phase1/network/services/batch_signature_verification.go [hunk 1]
```diff
@@ -54,27 +53,26 @@ func (b *BatchSignatureVerifier) AddVerification(aggregateVerificationData *Aggr
...
 	aggregateVerificationData := make([]*AggregateVerificationData, 0, 128)
 	for {
 		select {
 		case <-b.ctx.Done():
 			return
 		case verification := <-b.verifyAndExecute:
-			b.size += uint64(len(verification.Signatures))
 			aggregateVerificationData = append(aggregateVerificationData, verification)
-			if b.size > BatchSignatureVerificationThreshold {
+			if len(aggregateVerificationData) > BatchSignatureVerificationThreshold {
```
Comment (shotasilagadze) [inline cl/phase1/network/services/batch_signature_verification.go:64]: I wanted to use `b.size` because we don't know how many signatures we are verifying otherwise because in each `AggregateVerificationData` there might be 1 transaction or 3 (or in the future 100 🤷 ).

That's why I was looking into it with `len(verification.Signatures)` and was verifying when I had specific number of transactions and not `AggregateVerificationData`.

But this should also work

File: cl/phase1/network/services/aggregate_and_proof_service.go [hunk 2]
```diff
@@ -179,6 +210,7 @@ func (a *aggregateAndProofServiceImpl) ProcessMessage(
 			aggregateAndProof.SignedAggregateAndProof.Message.Aggregate,
 			attestingIndicies,
 		)
+		a.seenAggreatorIndexes.Add(seenIndex, struct{}{})
```
Comment (shotasilagadze) [inline cl/phase1/network/services/aggregate_and_proof_service.go:213]: Shouldn't we clean this after some time?

File: cl/phase1/network/services/batch_signature_verification.go (hunk 1 above)
Comment (Giulio2002) [reply cl/phase1/network/services/batch_signature_verification.go:64]: I think this tells us better about our memory cap. as you say, if you have b.size = 100 but have actually 1000 signatures, then it might not be expected

File: cl/phase1/network/services/aggregate_and_proof_service.go (hunk 2 above)
Comment (Giulio2002) [reply cl/phase1/network/services/aggregate_and_proof_service.go:213]: it is an lru cache it gets automatically cleaned already, after n elements

**Review by domiwei — APPROVED** [review]
