### PR TITLE
Torrent performance and misc downloader tweaks

### LINKED ISSUE #16274: 3.0 to 3.1 log errors
@wmitsuda found in testing migration from 3.0 to 3.1 some useful errors:

```
INFO[07-21|16:23:15.375] [1/6 OtterSync] Syncing                  file-metadata=218/218 files=160/218 data="67.51% - 7.8GB/11.6GB" time-left=0s total-time=3s download-rate=27.6MB/s hashing-rate=24.5MB/s alloc=68
.5MB sys=191.7MB
INFO[07-21|16:23:19.361] [1/6 OtterSync] Syncing                  file-metadata=218/218 files=161/218 data="69.81% - 8.1GB/11.6GB" time-left=52s total-time=7s download-rate=67.9MB/s hashing-rate=67.0MB/s alloc=9
9.0MB sys=321.2MB
EROR[07-21|16:23:22.393] error marking piece complete             torrent.name=v1.0-022500-022600-headers.seg torrent.ih=e949303362f44c7653c59a1b7ad595b73dd4ad9d piece=25 err="error promoting part file \"/Users/
wmitsuda/eth-nodes/erigon3-mainnet-migration/snapshots/v1.0-022500-022600-headers.seg\": source and destination files both exist"
INFO[07-21|16:23:27.361] [1/6 OtterSync] Syncing                  file-metadata=218/218 files=161/218 data="74.58% - 8.6GB/11.6GB" time-left=42s total-time=15s download-rate=70.7MB/s hashing-rate=70.9MB/s alloc=
149.1MB sys=385.2MB
EROR[07-21|16:23:35.166] error marking piece complete             torrent.name=v1.0-022910-022920-headers.idx torrent.ih=6a82b1250bd865263e8177cd7b6a4115c8098271 piece=0 err="error promoting part file \"/Users/w
mitsuda/eth-nodes/erigon3-mainnet-migration/snapshots/v1.0-022910-022920-headers.idx\": source and destination files both exist"
CRIT[07-21|16:23:35.166] snapshot file has wrong size             name=v1.0-022910-022920-headers.idx expected=46567 actual=46591
WARN[07-21|16:23:35.167] torrent failed metainfo commit precheck  err="completed torrent failed validation" name=v1.0-022910-022920-headers.idx
EROR[07-21|16:23:35.167] error marking piece complete             torrent.name=v1.0-022910-022920-headers.idx torrent.ih=6a82b1250bd865263e8177cd7b6a4115c8098271 piece=0 err="error promoting part file \"/Users/w
mitsuda/eth-nodes/erigon3-mainnet-migration/snapshots/v1.0-022910-022920-headers.idx\": source and destination files both exist"
INFO[07-21|16:23:43.361] [1/6 OtterSync] Syncing                  file-metadata=218/218 files=168/218 data="84.27% - 9.7GB/11.6GB" time-left=25s total-time=31s download-rate=71.8MB/s hashing-rate=71.3MB/s alloc=
208.3MB sys=385.2MB
```

For more, https://discord.com/channels/1133875232453693480/1356926710502916096/1396937294681997444.

This issue tracks fixing the individual items.

### PR DESCRIPTION
**Pull request by anacrolix**
Should fix #16274 and #16384.

Should help with #16151.

Also fixes a case where uploading/seeding isn't handled well and caused very high scheduler overhead. It may have caused gradual performance decline over time, I noticed it on long-running nodes.

https://github.com/anacrolix/torrent/compare/master...anacrolix

There's a few changes of @AskAlexSharov, I will leave them in.

Fixes excessive piece hashing routines being spawned.

Exposes a few variables that modify webseed HTTP client to help pin down why OVH is being throttled.

Fixes a case where torrents added from disk can race against be "required" to proceed past a sync stage. This seemed to cause hashing errors due to races.

Fix an annoying log message about `"initialized downloads", "torrents": 0` for snapshots added by non-sync services, that just happen to be adding nothing.

Fix a few invariants that weren't checked correctly in anacrolix/torrent.

### CODE REVIEW

File: cmd/erigon/main.go [hunk 1]
```diff
@@ -38,6 +40,7 @@ import (
 
 func main() {
 	defer envpprof.Stop()
+	http.DefaultServeMux.Handle("/debug/fgprof", fgprof.Handler())
```
Comment (AskAlexSharov) [inline cmd/erigon/main.go:43]: it's in `pprofMux.Handle("/debug/fgprof", fgprof.Handler())`

**Comment by wmitsuda** [comment]
logs

[torrent.log](https://github.com/user-attachments/files/21478527/torrent.log)

**Comment by wmitsuda** [comment]
logs

[torrent.log.gz](https://github.com/user-attachments/files/21478537/torrent.log.gz)

**Comment by anacrolix** [comment]
@wmitsuda there might have been a race in resuming the downloader causing some of the errors in your torrent log. https://github.com/erigontech/erigon/pull/16328/commits/999f92b68f444afe4f351a864021e911125622f8 should fix that.

**Comment by wmitsuda** [comment]
no improvement on commit `334b16aa987f2f5d46ca46be4b73c3bf4577f6c0`

logs:

```
INFO[07-29|16:03:23.621] [1/1 OtterSync] Syncing                  file-metadata=1373/1373 files=2/1373 data="0.98% - 338.2MB/33.7GB" time-left=1h53m13s total-time=3m0s download-rate=4.8MB/s hashing-rate=4.8MB/s
alloc=177.2MB sys=584.4MB
INFO[07-29|16:03:58.479] [1/1 OtterSync] Syncing                  file-metadata=1373/1373 files=2/1373 data="1.47% - 509.0MB/33.7GB" time-left=1h43m32s total-time=3m35s download-rate=5.6MB/s hashing-rate=5.3MB/s
 alloc=320.4MB sys=584.8MB
INFO[07-29|16:04:27.934] [1/1 OtterSync] Syncing                  file-metadata=1373/1373 files=8/1373 data="1.90% - 654.6MB/33.7GB" time-left=1h50m59s total-time=4m4s download-rate=5.2MB/s hashing-rate=5.4MB/s
```

torrent.log:

[torrent.log.gz](https://github.com/user-attachments/files/21495896/torrent.log.gz)

**Comment by anacrolix** [comment]
@wmitsuda are you running on any OVH VPS? Can you run with `DOWNLOADER_MAX_CONNS_PER_HOST=10` or `20`? It looks like the issue is your client is getting rejected or failing to retrieve the metainfos it needs to proceed. Can you also provide the output of `/downloader/torrentClientStatus` once the client settles down to those bad speeds (~5MB/s). Thanks!

**Comment by wmitsuda** [comment]
> @wmitsuda are you running on any OVH VPS? Can you run with `DOWNLOADER_MAX_CONNS_PER_HOST=10` or `20`? It looks like the issue is your client is getting rejected or failing to retrieve the metainfos it needs to proceed. Can you also provide the output of `/downloader/torrentClientStatus` once the client settles down to those bad speeds (~5MB/s). Thanks!

no, I'm running it on my macbook. and it works fine on 3.0.15, does that give any insight?

**Comment by AskAlexSharov** [comment]
let's work based on `release/3.1` branch - because I can't start `main` on snapshotters (it may break them). later will cherry-pick to main.

**Comment by wmitsuda** [comment]
it seems latest commit has compilation errors (ignore the dir name, I'm using this PR's branch):

```
make
Building /Users/wmitsuda/erigon3-main/build/bin/erigon
cd ./cmd/erigon && GOARCH=arm64  CGO_CFLAGS="-O2 -g  -DMDBX_FORCE_ASSERTIONS=0  -DMDBX_DISABLE_VALIDATION=0  -DMDBX_ENV_CHECKPID=0  -D__BLST_PORTABLE__ -Wno-unknown-warning-option -Wno-enum-int-mismatch -Wno-strict-prototypes -Wno-unused-but-set-variable -O3" CGO_LDFLAGS="-O2 -g -O3 -g" GOPRIVATE="github.com/erigontech/silkworm-go" go  build -trimpath -buildvcs=false -ldflags "-X github.com/erigontech/erigon/params.GitCommit=2d2058a9816570544d2c541b8c012f7306186c1f -X github.com/erigontech/erigon/params.GitBranch=anacrolix/main-torrent-perf -X github.com/erigontech/erigon/params.GitTag=v3.0.0-beta1-1292-g2d2058a"  -tags , -o /Users/wmitsuda/erigon3-main/build/bin/erigon
# github.com/erigontech/erigon-db/downloader
../../erigon-db/downloader/downloader.go:303:19: cfg.ClientConfig.MetainfoSourcesClient undefined (type *torrent.ClientConfig has no field or method MetainfoSourcesClient)
../../erigon-db/downloader/downloader.go:636:54: connStats.WebSeeds undefined (type torrent.ClientStats has no field or method WebSeeds)
../../erigon-db/downloader/downloader.go:637:49: connStats.PeerConns undefined (type torrent.ClientStats has no field or method PeerConns)
make: *** [erigon.cmd] Error 1
```

**Comment by wmitsuda** [comment]
> @wmitsuda are you running on any OVH VPS? Can you run with `DOWNLOADER_MAX_CONNS_PER_HOST=10` or `20`? It looks like the issue is your client is getting rejected or failing to retrieve the metainfos it needs to proceed. Can you also provide the output of `/downloader/torrentClientStatus` once the client settles down to those bad speeds (~5MB/s). Thanks!

anyway, running using yesterday's code, I see not improvement with DOWNLOADER_MAX_CONNS_PER_HOST=10, a little improvement with 20 (log shows +10MB/s)

which endpoint is the `/downloader/torrentClientStatus`? (that's why I asked about external downloader on discord)

I found out about `--downloader.api.addr`, but I think it is not that one, right?

**Comment by anacrolix** [comment]
> anyway, running using yesterday's code, I see not improvement with DOWNLOADER_MAX_CONNS_PER_HOST=10, a little improvement with 20 (log shows +10MB/s)

Try latest and play with `TORRENT_WEBSEED_HOST_REQUEST_CONCURRENCY=50`.

> which endpoint is the `/downloader/torrentClientStatus`? (that's why I asked about external downloader on discord)

I think it's exposed to pprof or metrics mux, or I just use [`GOPPROF=http`](https://github.com/anacrolix/envpprof).

**Comment by wmitsuda** [comment]
found it:
[status.txt.gz](https://github.com/user-attachments/files/21553720/status.txt.gz)

**Comment by wmitsuda** [comment]
TORRENT_WEBSEED_HOST_REQUEST_CONCURRENCY didn't work (much). I see some peaks of 70-80MB/s, but in general it remains on ~10-20MB/s.

image

**Comment by wmitsuda** [comment]
torrent.log is empty now

**Comment by wmitsuda** [comment]
download speed dropped to 0 ~15min ago and remains:

```
INFO[08-01|19:04:00.126] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=67h7m44s total-time=2h39m13s webseed-download=19.9MB/s peer-downlo
ad=0B/s combined-download-todo-remove=19.9MB/s upload=0B/s hashing-rate=2.7MB/s alloc=2.8GB sys=5.1GB
INFO[08-01|19:04:19.389] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=337h14m13s total-time=2h39m32s webseed-download=4.0MB/s peer-downl
oad=0B/s combined-download-todo-remove=4.0MB/s upload=0B/s hashing-rate=13.5MB/s alloc=3.3GB sys=5.1GB
INFO[08-01|19:04:49.364] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=∞ total-time=2h40m2s webseed-download=0B/s peer-download=0B/s comb
ined-download-todo-remove=0B/s upload=0B/s hashing-rate=12.9MB/s alloc=3.6GB sys=5.1GB
INFO[08-01|19:05:15.541] [p2p] GoodPeers                          eth68=23 eth67=27
INFO[08-01|19:05:19.027] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=∞ total-time=2h40m32s webseed-download=0B/s peer-download=0B/s com
bined-download-todo-remove=0B/s upload=0B/s hashing-rate=12.5MB/s alloc=2.8GB sys=5.1GB
INFO[08-01|19:05:49.031] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=∞ total-time=2h41m2s webseed-download=0B/s peer-download=0B/s comb
ined-download-todo-remove=0B/s upload=0B/s hashing-rate=9.2MB/s alloc=3.5GB sys=5.1GB
INFO[08-01|19:06:18.536] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=∞ total-time=2h41m32s webseed-download=0B/s peer-download=0B/s com
bined-download-todo-remove=0B/s upload=0B/s hashing-rate=15.5MB/s alloc=4.0GB sys=5.1GB
```

I'll let it running for a few hours untouched just to see what happens. let me know if you need me to get some data from it.

**Comment by wmitsuda** [comment]
update: webseed working again after ~50 min

**Comment by anacrolix** [comment]
> download speed dropped to 0 ~15min ago and remains:
> 
> ```
> INFO[08-01|19:04:00.126] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=67h7m44s total-time=2h39m13s webseed-download=19.9MB/s peer-downlo
> ad=0B/s combined-download-todo-remove=19.9MB/s upload=0B/s hashing-rate=2.7MB/s alloc=2.8GB sys=5.1GB
> INFO[08-01|19:04:19.389] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=337h14m13s total-time=2h39m32s webseed-download=4.0MB/s peer-downl
> oad=0B/s combined-download-todo-remove=4.0MB/s upload=0B/s hashing-rate=13.5MB/s alloc=3.3GB sys=5.1GB
> INFO[08-01|19:04:49.364] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=∞ total-time=2h40m2s webseed-download=0B/s peer-download=0B/s comb
> ined-download-todo-remove=0B/s upload=0B/s hashing-rate=12.9MB/s alloc=3.6GB sys=5.1GB
> INFO[08-01|19:05:15.541] [p2p] GoodPeers                          eth68=23 eth67=27
> INFO[08-01|19:05:19.027] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=∞ total-time=2h40m32s webseed-download=0B/s peer-download=0B/s com
> bined-download-todo-remove=0B/s upload=0B/s hashing-rate=12.5MB/s alloc=2.8GB sys=5.1GB
> INFO[08-01|19:05:49.031] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=∞ total-time=2h41m2s webseed-download=0B/s peer-download=0B/s comb
> ined-download-todo-remove=0B/s upload=0B/s hashing-rate=9.2MB/s alloc=3.5GB sys=5.1GB
> INFO[08-01|19:06:18.536] [1/1 OtterSync] Syncing                  file-metadata=6829/6829 files=1401/6829 data="5.77% - 274.6GB/4.6TB" time-left=∞ total-time=2h41m32s webseed-download=0B/s peer-download=0B/s com
> bined-download-todo-remove=0B/s upload=0B/s hashing-rate=15.5MB/s alloc=4.0GB sys=5.1GB
> ```
> 
> I'll let it running for a few hours untouched just to see what happens. let me know if you need me to get some data from it.

When this happens, can you please get a goroutine dump? `/debug/pprof/goroutines`. The fix should be f93561e6388112c8c4a8ee2d0a183cfbf6dbbb8e but the dump will confirm for me.

**Comment by anacrolix** [comment]
Please don't merge, I have a few followup fixes.

**Comment by wmitsuda** [comment]
latest logs, after a few runs after having caching activated.

no improvement even with plenty of hits, but got some interesting logs

[logs.tgz](https://github.com/user-attachments/files/21584286/logs.tgz)

**Comment by anacrolix** [comment]
* Files are now finished in a deterministic order to minimize part files on disk.
* Massively improved initial piece hashing performance, and a bunch of other filesystem activity.
* Exposed a ton of knobs to tune behaviour.
* Fixed a nasty bug when hashing isn't performed or delayed after a torrent is added.

Outstanding:
* There's still an issue with requests hanging in the CF infrastructure. There's no timeouts to tune for this, I need a sloloris detector or just a heavy context over whole requests.
* Performance still sits at about ~350MB/s tops. I did make file ordering more deterministic so I may have switched to a cold set of files for regarding caching for now.

**Comment by AskAlexSharov** [comment]
```
oad=58.4MB/s peer-download=0B/s combined-download-todo-remove=58.4MB/s upload=0B/s hashing-rate=58.6MB/s alloc=8.0GB sys=8.2GB
panic: is zero

goroutine 1037271 [running]:
github.com/anacrolix/missinggo/v2/panicif.Zero[...](...)
	github.com/anacrolix/missinggo/v2@v2.10.0/panicif/panicif.go:112
github.com/anacrolix/torrent.(*Client).updateWebseedRequests.func2({{{{0xc081ad8ae0}, 0xc08a780908, 0x0}, 0xb0}, {{0xc081ad8af0}, 0xc1e7e55db0, 0x0}, 0x1}, {{{{0xc081ad8ae0}, 0xc08a780908, ...}, ...}, ...})
	github.com/anacrolix/torrent@v1.58.2-0.20250805140032-23f52690acff/webseed-requesting.go:142 +0x2ce
github.com/anacrolix/generics/heap.sliceInterface[...].Less(...)
	github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/slice.go:11
github.com/anacrolix/generics/heap.down[...]({0x3b78080?, 0xc214fd5a70}, 0x15, 0x2d)
	github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/heap.go:108 +0xb0
github.com/anacrolix/generics/heap.Init[...]({0x3b78080, 0xc214fd5a70})
	github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/heap.go:45 +0x5d
github.com/anacrolix/torrent.(*Client).updateWebseedRequests(0xc000ae7608)
	github.com/anacrolix/torrent@v1.58.2-0.20250805140032-23f52690acff/webseed-requesting.go:149 +0xa05
github.com/anacrolix/torrent.(*Client).updateWebseedRequestsAndResetTimer.func1({0x3b6f678?, 0xc214ceb920?})
	github.com/anacrolix/torrent@v1.58.2-0.20250805140032-23f52690acff/webseed-requesting.go:475 +0x8d
runtime/pprof.Do({0x3b6f120?, 0x6bad580?}, {{0xc214ce6720?, 0x3b524a0?, 0xbcd800?}}, 0xc1d2b93f30)
	runtime/pprof/runtime.go:51 +0x8c
github.com/anacrolix/torrent.(*Client).updateWebseedRequestsAndResetTimer(0xc000ae7608)
	github.com/anacrolix/torrent@v1.58.2-0.20250805140032-23f52690acff/webseed-requesting.go:469 +0x9c
github.com/anacrolix/torrent.(*Client).updateWebseedRequestsTimerFunc(0xc000ae7608)
	github.com/anacrolix/torrent@v1.58.2-0.20250805140032-23f52690acff/webseed-requesting.go:465 +0xf9
created by time.goFunc
	time/sleep.go:215 +0x2d
Finished with result: exit-code
```

**Comment by AskAlexSharov** [comment]
was able to sync.

- at start on empty datadir see: 
```
[WARN] [08-06|03:38:45.054] eb3c88866986745db8052845882e9dae296cb36c: error hashing piece 0: open /erigon-data/remove_me_experiment/snapshots/salt-blocks.txt: no such file or directory names="[eb3c88866986745db8052845882e9dae296cb36c hashing github.com/anacrolix/torrent torrent.go:2783]"
```

sometime see (at DOWNLOADER_MAX_CONNS_PER_HOST=20, didn't measure another):
```
[WARN] [08-06|03:41:04.707] unexpected identity response Content-Length value torrent.name=domain/v1.0-accounts.0-2048.kv torrent.ih=82a39df157f5ca62c51ccc4cd864cba4e1d93124 webseed=https://erigon31-v1-snapshots-bor-mainnet.erigon.network/ actual=14920714445 expected=67108864 url=https://erigon31-v1-snapshots-bor-mainnet.erigon.network/domain%2Fv1.0-accounts.0-2048.kv
```

speed:
```
file-metadata=7085/7085 files=1382/7085 data="1.84% - 110.3GB/5.9TB" time-left=3h43m40s total-time=4m41s webseed-download=450.3MB/s
```
@wmitsuda what is your speed?

**Comment by anacrolix** [comment]
> was able to sync.
> 
> * at start on empty datadir see:
> 
> ```
> [WARN] [08-06|03:38:45.054] eb3c88866986745db8052845882e9dae296cb36c: error hashing piece 0: open /erigon-data/remove_me_experiment/snapshots/salt-blocks.txt: no such file or directory names="[eb3c88866986745db8052845882e9dae296cb36c hashing github.com/anacrolix/torrent torrent.go:2783]"
> ```

https://github.com/anacrolix/torrent/commit/e05f9a1ff4adcc1d76198c2f3f08c84a88a4523e

> 
> sometime see (at DOWNLOADER_MAX_CONNS_PER_HOST=20, didn't measure another):
> 
> ```
> [WARN] [08-06|03:41:04.707] unexpected identity response Content-Length value torrent.name=domain/v1.0-accounts.0-2048.kv torrent.ih=82a39df157f5ca62c51ccc4cd864cba4e1d93124 webseed=https://erigon31-v1-snapshots-bor-mainnet.erigon.network/ actual=14920714445 expected=67108864 url=https://erigon31-v1-snapshots-bor-mainnet.erigon.network/domain%2Fv1.0-accounts.0-2048.kv
> ```

I saw that early on, I haven't seen it for a while since relying on http2 more. I think it occurs if there are lots of separate TCP connections. There's a check in the webseed code that content lengths are correct so that bad snapshots are detected quickly for simple file size mismatches. It should be harmless, but let me know if it causes issues.

> 
> speed:
> 
> ```
> file-metadata=7085/7085 files=1382/7085 data="1.84% - 110.3GB/5.9TB" time-left=3h43m40s total-time=4m41s webseed-download=450.3MB/s
> ```

🎉 

> 
> @wmitsuda what is your speed?

**Comment by anacrolix** [comment]
> ```
> oad=58.4MB/s peer-download=0B/s combined-download-todo-remove=58.4MB/s upload=0B/s hashing-rate=58.6MB/s alloc=8.0GB sys=8.2GB
> panic: is zero
> 
> goroutine 1037271 [running]:
> github.com/anacrolix/missinggo/v2/panicif.Zero[...](...)
> 	github.com/anacrolix/missinggo/v2@v2.10.0/panicif/panicif.go:112
> github.com/anacrolix/torrent.(*Client).updateWebseedRequests.func2({{{{0xc081ad8ae0}, 0xc08a780908, 0x0}, 0xb0}, {{0xc081ad8af0}, 0xc1e7e55db0, 0x0}, 0x1}, {{{{0xc081ad8ae0}, 0xc08a780908, ...}, ...}, ...})
> 	github.com/anacrolix/torrent@v1.58.2-0.20250805140032-23f52690acff/webseed-requesting.go:142 +0x2ce
> github.com/anacrolix/generics/heap.sliceInterface[...].Less(...)
> 	github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/slice.go:11
> github.com/anacrolix/generics/heap.down[...]({0x3b78080?, 0xc214fd5a70}, 0x15, 0x2d)
> 	github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/heap.go:108 +0xb0
> github.com/anacrolix/generics/heap.Init[...]({0x3b78080, 0xc214fd5a70})
> 	github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/heap.go:45 +0x5d
> github.com/anacrolix/torrent.(*Client).updateWebseedRequests(0xc000ae7608)
> 	github.com/anacrolix/torrent@v1.58.2-0.20250805140032-23f52690acff/webseed-requesting.go:149 +0xa05
> github.com/anacrolix/torrent.(*Client).updateWebseedRequestsAndResetTimer.func1({0x3b6f678?, 0xc214ceb920?})
> 	github.com/anacrolix/torrent@v1.58.2-0.20250805140032-23f52690acff/webseed-requesting.go:475 +0x8d
> runtime/pprof.Do({0x3b6f120?, 0x6bad580?}, {{0xc214ce6720?, 0x3b524a0?, 0xbcd800?}}, 0xc1d2b93f30)
> 	runtime/pprof/runtime.go:51 +0x8c
> github.com/anacrolix/torrent.(*Client).updateWebseedRequestsAndResetTimer(0xc000ae7608)
> 	github.com/anacrolix/torrent@v1.58.2-0.20250805140032-23f52690acff/webseed-requesting.go:469 +0x9c
> github.com/anacrolix/torrent.(*Client).updateWebseedRequestsTimerFunc(0xc000ae7608)
> 	github.com/anacrolix/torrent@v1.58.2-0.20250805140032-23f52690acff/webseed-requesting.go:465 +0xf9
> created by time.goFunc
> 	time/sleep.go:215 +0x2d
> Finished with result: exit-code
> ```

Should be https://github.com/anacrolix/torrent/commit/5b8f5d7db4222ff1fb3f535f8f14ece132251a0b 🤞🏻

**Comment by anacrolix** [comment]
I picked your error wrappers and disabled perfsprint.

**Review by AskAlexSharov — APPROVED** [review]

**Comment by wmitsuda** [comment]
the latest of this PR didn't improve for me, however I accidentally may figured something new.

Because polygon is so huge, I sync it on an external SSD.

This is how it looks like on 3.0.15. Notice (that may be an important detail!) that it takes more than 10 minutes after the start for it to start doing any download.

But once it happens, it fully utilizes my bandwidth.

```
Polygon-external-3.0.15

INFO[08-07|05:55:34.602] Mapped network port                      proto=udp extport=34104 intport=34104 interface="UPNP IGDv1-PPP1"
INFO[08-07|05:55:35.009] Mapped network port                      proto=tcp extport=34103 intport=34103 interface="UPNP IGDv1-PPP1"
INFO[08-07|05:55:35.537] Mapped network port                      proto=udp extport=34103 intport=34103 interface="UPNP IGDv1-PPP1"
INFO[08-07|05:56:05.327] [1/1 OtterSync] Downloading              progress="(0/1373 files) 0.00% - 0B/0B" time-left=999hrs:99m total-time=37s download-rate=0B/s completion-rate=0B/s alloc=129.4MB sys=354.0MB
INFO[08-07|05:56:58.101] [p2p] GoodPeers                          eth68=4 eth67=1
INFO[08-07|05:58:28.248] [mem] memory stats                       alloc=203.4MB sys=372.7MB
INFO[08-07|05:58:28.248] [p2p] GoodPeers                          eth68=6 eth67=2
INFO[08-07|05:58:28.248] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=203.7MB sys=372.7MB
INFO[08-07|05:59:58.099] [p2p] GoodPeers                          eth68=12 eth67=6
INFO[08-07|06:01:28.847] [mem] memory stats                       alloc=260.8MB sys=540.5MB
INFO[08-07|06:01:28.847] [p2p] GoodPeers                          eth68=14 eth67=9
INFO[08-07|06:01:28.847] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=261.0MB sys=540.5MB
INFO[08-07|06:02:58.097] [p2p] GoodPeers                          eth67=13 eth68=16
INFO[08-07|06:04:28.247] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=335.5MB sys=623.1MB
INFO[08-07|06:04:28.248] [mem] memory stats                       alloc=335.5MB sys=623.1MB
INFO[08-07|06:04:28.247] [p2p] GoodPeers                          eth68=19 eth67=17
INFO[08-07|06:05:58.095] [p2p] GoodPeers                          eth67=22 eth68=21
INFO[08-07|06:07:26.346] [snapshots] no progress yet              files=1373 list=v1-069100-069200-bodies.seg,v1-071300-071400-bodies.idx,v1-071600-071700-headers.idx,v1-062600-062700-headers.idx,v1-015000-01550
0-bodies.seg,...
INFO[08-07|06:07:26.356] [snapshots] no progress yet              files=1373 list=v1-028000-028500-headers.seg,v1-062600-062700-bodies.idx,v1-067500-067600-headers.idx,v1-072900-073000-bodies.idx,v1-074044-07404
5-headers.idx,...
INFO[08-07|06:07:26.356] [1/1 OtterSync] Downloading              progress="(1373/1373 files) 0.00% - 0B/33.4GB" time-left=999hrs:99m total-time=11m58s download-rate=0B/s completion-rate=0B/s alloc=493.2MB sys=9
92.5MB
INFO[08-07|06:07:28.094] [1/1 OtterSync] Downloading              progress="(1373/1373 files) 0.00% - 0B/33.4GB" time-left=999hrs:99m total-time=12m0s download-rate=0B/s completion-rate=0B/s alloc=1.3GB sys=1.8G
B
INFO[08-07|06:07:28.094] [mem] memory stats                       alloc=1.3GB sys=1.8GB
INFO[08-07|06:07:28.094] [p2p] GoodPeers                          eth68=23 eth67=24
INFO[08-07|06:07:28.111] [snapshots] no progress yet              files=1348 list=v1-056500-056600-headers.seg,v1-057400-057500-headers.seg,v1-057800-057900-headers.seg,v1-073300-073400-headers.seg,v1-059600-059
700-headers.idx,...
INFO[08-07|06:07:28.151] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=1.3GB sys=1.8GB
INFO[08-07|06:07:48.094] [1/1 OtterSync] Downloading              progress="(1373/1373 files) 0.11% - 37.4MB/33.4GB" time-left=102hrs:37m total-time=12m20s download-rate=94.8KB/s completion-rate=0B/s alloc=5.4GB
sys=5.9GB
INFO[08-07|06:07:48.109] [snapshots] no progress yet              files=1044 list=v1-053300-053400-bodies.seg,v1-054500-054600-bodies.idx,v1-058000-058100-headers.seg,v1-058800-058900-headers.seg,v1-059500-05960
0-headers.idx,...
INFO[08-07|06:08:08.141] [1/1 OtterSync] Downloading              progress="(1373/1373 files) 5.07% - 1.7GB/33.4GB" time-left=0hrs:6m total-time=12m40s download-rate=84.9MB/s completion-rate=84.6MB/s alloc=6.2GB
sys=6.5GB
INFO[08-07|06:08:08.157] [snapshots] no progress yet              files=1043 list=v1-055500-055600-bodies.idx,v1-056000-056100-headers.idx,v1-057100-057200-bodies.seg,v1-062100-062200-headers.idx,v1-072000-07210
0-headers.seg,... 
```

polygon-external-3 0 15

The following is what happens with this PR on the same disk. It is always slow.

```
Polygon-external-PR3.1

INFO[08-07|06:43:59.156] [1/1 OtterSync] Syncing                  file-metadata=1373/1373 files=284/1373 data="98.31% - 33.1GB/33.7GB" time-left=19s total-time=21m30s webseed-download=29.4MB/s peer-download=0B/s
hashing-rate=11.3MB/s peers=0 conns=0 upload=0B/s alloc=566.0MB sys=923.9MB
2025-08-07 06:43:59.222181 -0300 -03 m=+1296.849010501: updateWebseedRequests took 825.291µs (reason: timer)
2025-08-07 06:44:04.223009 -0300 -03 m=+1301.849838626: updateWebseedRequests took 773.541µs (reason: timer)
2025-08-07 06:44:09.224072 -0300 -03 m=+1306.850901460: updateWebseedRequests took 750.75µs (reason: timer)
2025-08-07 06:44:14.226411 -0300 -03 m=+1311.853239918: updateWebseedRequests took 2.221625ms (reason: timer)
2025-08-07 06:44:19.227392 -0300 -03 m=+1316.854221335: updateWebseedRequests took 750.084µs (reason: timer)
2025-08-07 06:44:24.228082 -0300 -03 m=+1321.854911001: updateWebseedRequests took 663.166µs (reason: timer)
INFO[08-07|06:44:28.759] [1/1 OtterSync] Syncing                  file-metadata=1373/1373 files=289/1373 data="99.82% - 33.6GB/33.7GB" time-left=3s total-time=22m0s webseed-download=17.3MB/s peer-download=0B/s h
ashing-rate=8.4MB/s peers=0 conns=0 upload=0B/s alloc=453.5MB sys=923.9MB 
```

But something interesting happens if I try this same PR on the native macbook pro NVME. It is almost the same speed as 3.0.15, see:

```
 Polygon-internal-PR3.1 

 INFO[08-07|07:01:15.383] [1/1 OtterSync] Syncing                  file-metadata=1373/1373 files=286/1373 data="35.61% - 12.0GB/33.7GB" time-left=4m29s total-time=2m30s webseed-download=82.6MB/s peer-download=0B/
s hashing-rate=82.8MB/s peers=0 conns=0 upload=0B/s alloc=236.6MB sys=568.0MB
2025-08-07 07:01:19.947286 -0300 -03 m=+160.362382376: updateWebseedRequests took 13.771208ms (reason: timer)
time=2025-08-07T07:01:20.222-03:00 level=DEBUG [source=github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed/client.go:135](http://source=github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed/client.go:135) msg="request for part" webseedUrl=https://erigon31-v1-snapshots-bor-/
m
```

polygon-internal-PR3 1

So, I'm guessing:

- Something changed in 3.1 that slower disks become the bottleneck, maybe writing the pieces on disk is actually delaying the whole process.
- That should not affect it, as it was working perfectly on 3.0.15, it is possible to have fast downloads on slower disks.
- interesting fact that 3.0.15 takes 10 min to start downloads, maybe the old behavior was to do some warm up hence it was always fast when the downloader started writing the pieces?

**Comment by wmitsuda** [comment]
I just got a panic using the latest of this PR:

```
2025-08-07 07:39:44.506359 -0300 -03 m=+578.358652710: updateWebseedRequests took 2.063917ms (reason: timer)
(torrent.heapElem) {
 webseedUniqueRequestKey: (torrent.webseedUniqueRequestKey) {{0x340033b3f50} 0x3400190ad08 0} at 0:144,
 webseedRequestOrderValue: (torrent.webseedRequestOrderValue) torrent.webseedRequestOrderValue{costKey:unique.Handle[github.com/anacrolix/torrent.webseedHostKey]{value:(*torrent.webseedHostKey)(0x340033b3f60)},
existingWebseedRequest:(*torrent.webseedRequest)(0xb401ab16190), priority:0x1},
 mightHavePartialFiles: (bool) true
}
(torrent.heapElem) {
 webseedUniqueRequestKey: (torrent.webseedUniqueRequestKey) {{0x340033b3f50} 0x3400190ad08 0} at 0:145,
 webseedRequestOrderValue: (torrent.webseedRequestOrderValue) torrent.webseedRequestOrderValue{costKey:unique.Handle[github.com/anacrolix/torrent.webseedHostKey]{value:(*torrent.webseedHostKey)(0x340033b3f60)},
existingWebseedRequest:(*torrent.webseedRequest)(0xb4020f14e10), priority:0x1},
 mightHavePartialFiles: (bool) true
}
panic: webseed request heap ordering is not stable

goroutine 295495 [running]:
github.com/anacrolix/torrent.(*Client).updateWebseedRequests.func2({{{{0x340033b3f50}, 0x3400190ad08, 0x0}, 0x90}, {{0x340033b3f60}, 0xb401ab16190, 0x1}, 0x1}, {{{{0x340033b3f50}, 0x3400190ad08, ...}, ...}, ...}
)
        github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed-requesting.go:147 +0x374
github.com/anacrolix/generics/heap.sliceInterface[...].Less(...)
        github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/slice.go:11
github.com/anacrolix/generics/heap.down[...]({0x1075c64c0?, 0xb401ab11690}, 0x19, 0x6d)
        github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/heap.go:108 +0xac
github.com/anacrolix/generics/heap.Init[...]({0x1075c64c0, 0xb401ab11690})
        github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/heap.go:45 +0x68
github.com/anacrolix/torrent.(*Client).updateWebseedRequests(0x14000bcd708)
        github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed-requesting.go:155 +0x780
github.com/anacrolix/torrent.(*Client).updateWebseedRequestsAndResetTimer.func1({0x1075bde18?, 0xb403c42e930?})
        github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed-requesting.go:487 +0x70
runtime/pprof.Do({0x1075bd8d0?, 0x10a31a9a0?}, {{0x140025c3840?, 0x104b7d54c?, 0x106099604?}}, 0x34003888f18)
        runtime/pprof/runtime.go:51 +0x78
github.com/anacrolix/torrent.(*Client).updateWebseedRequestsAndResetTimer(0x14000bcd708)
        github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed-requesting.go:481 +0x90
github.com/anacrolix/torrent.(*Client).updateWebseedRequestsTimerFunc(0x14000bcd708)
        github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed-requesting.go:477 +0x104
created by time.goFunc
        time/sleep.go:215 +0x38
```

**Comment by anacrolix** [comment]
> the latest of this PR didn't improve for me, however I accidentally may figured something new.
> 
> Because polygon is so huge, I sync it on an external SSD.
> 
> This is how it looks like on 3.0.15. Notice (that may be an important detail!) that it takes more than 10 minutes after the start for it to start doing any download.

That was my experience when I went back to try 3.0 to compare. It's just that the Downloader in 3.0 does extra handling and preparation around which files to do, and takes longer to get to the meatier files.

> 
> But once it happens, it fully utilizes my bandwidth.

Only ~80MB/s, I was thinking you had ~GB/s of bandwidth 😿 

> * Something changed in 3.1 that slower disks become the bottleneck, maybe writing the pieces on disk is actually delaying the whole process.
> * That should not affect it, as it was working perfectly on 3.0.15, it is possible to have fast downloads on slower disks.
> * interesting fact that 3.0.15 takes 10 min to start downloads, maybe the old behavior was to do some warm up hence it was always fast when the downloader started writing the pieces?

I suspect this will be the mmap storage. 3.0 used mmap, which will have gentler caching guarantees and ordering (and more corruption) that seems to differ on your machine. There might be a flag we can take advantage of for this. I could test on a slower disk too to reproduce it.

**Comment by anacrolix** [comment]
> I just got a panic using the latest of this PR:
> 
> ```
> 2025-08-07 07:39:44.506359 -0300 -03 m=+578.358652710: updateWebseedRequests took 2.063917ms (reason: timer)
> (torrent.heapElem) {
>  webseedUniqueRequestKey: (torrent.webseedUniqueRequestKey) {{0x340033b3f50} 0x3400190ad08 0} at 0:144,
>  webseedRequestOrderValue: (torrent.webseedRequestOrderValue) torrent.webseedRequestOrderValue{costKey:unique.Handle[github.com/anacrolix/torrent.webseedHostKey]{value:(*torrent.webseedHostKey)(0x340033b3f60)},
> existingWebseedRequest:(*torrent.webseedRequest)(0xb401ab16190), priority:0x1},
>  mightHavePartialFiles: (bool) true
> }
> (torrent.heapElem) {
>  webseedUniqueRequestKey: (torrent.webseedUniqueRequestKey) {{0x340033b3f50} 0x3400190ad08 0} at 0:145,
>  webseedRequestOrderValue: (torrent.webseedRequestOrderValue) torrent.webseedRequestOrderValue{costKey:unique.Handle[github.com/anacrolix/torrent.webseedHostKey]{value:(*torrent.webseedHostKey)(0x340033b3f60)},
> existingWebseedRequest:(*torrent.webseedRequest)(0xb4020f14e10), priority:0x1},
>  mightHavePartialFiles: (bool) true
> }
> panic: webseed request heap ordering is not stable
> 
> goroutine 295495 [running]:
> github.com/anacrolix/torrent.(*Client).updateWebseedRequests.func2({{{{0x340033b3f50}, 0x3400190ad08, 0x0}, 0x90}, {{0x340033b3f60}, 0xb401ab16190, 0x1}, 0x1}, {{{{0x340033b3f50}, 0x3400190ad08, ...}, ...}, ...}
> )
>         github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed-requesting.go:147 +0x374
> github.com/anacrolix/generics/heap.sliceInterface[...].Less(...)
>         github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/slice.go:11
> github.com/anacrolix/generics/heap.down[...]({0x1075c64c0?, 0xb401ab11690}, 0x19, 0x6d)
>         github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/heap.go:108 +0xac
> github.com/anacrolix/generics/heap.Init[...]({0x1075c64c0, 0xb401ab11690})
>         github.com/anacrolix/generics@v0.0.4-0.20250708073025-68393b391647/heap/heap.go:45 +0x68
> github.com/anacrolix/torrent.(*Client).updateWebseedRequests(0x14000bcd708)
>         github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed-requesting.go:155 +0x780
> github.com/anacrolix/torrent.(*Client).updateWebseedRequestsAndResetTimer.func1({0x1075bde18?, 0xb403c42e930?})
>         github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed-requesting.go:487 +0x70
> runtime/pprof.Do({0x1075bd8d0?, 0x10a31a9a0?}, {{0x140025c3840?, 0x104b7d54c?, 0x106099604?}}, 0x34003888f18)
>         runtime/pprof/runtime.go:51 +0x78
> github.com/anacrolix/torrent.(*Client).updateWebseedRequestsAndResetTimer(0x14000bcd708)
>         github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed-requesting.go:481 +0x90
> github.com/anacrolix/torrent.(*Client).updateWebseedRequestsTimerFunc(0x14000bcd708)
>         github.com/anacrolix/torrent@v1.58.2-0.20250806125636-548da6164834/webseed-requesting.go:477 +0x104
> created by time.goFunc
>         time/sleep.go:215 +0x38
> ```

That should be fixed, I forgot to move an assertion back to the correct location.

File: Makefile [hunk 2]
```diff
@@ -186,7 +186,7 @@ test-erigon-ext:
 ## test-short:                run short tests with a 10m timeout
 test-short: test-erigon-lib-short
 	@{ \
-		$(GOTEST) -short --timeout 10m -coverprofile=coverage-test.out > run.log 2>&1; \
```
Comment (taratorio) [inline Makefile:189]: @anacrolix we use coverprofile for sonar - why did you have to remove it?

Comment (taratorio) [reply Makefile:189]: oh actually - nevermind - we get that from `make test-all` actually not for `make test-short` - all good

Comment (anacrolix) [reply Makefile:189]: Yeah it burned a bunch of time for "short'
