### PR TITLE
building indexes on old files if have some

### LINKED ISSUE #16979: gnosis: Indexing failed
After starting erigon node built from the latest commit id in the `release/3.1` it printed ERRORs but proceed running.

Erigon build info:
```
[INFO] [09-03|07:37:14.705] Build info                               git_branch=release/3.1 git_tag=v3.1.0-rc1-22-ge229f0a git_commit=e229f0a2918b94a5c8770e2b163f010989d9bd13
```

```
[DBUG] [09-03|07:37:20.612] [removing] removing file                 path=/erigon-data/snapshots/v1.1-041867-041868-transactions-to-block.idx.tmp stack="[rw_dir.go:200 recsplit.go:253 block_types.go:339 type.go:68 type.go:274 type.go:396 snapshots.go:1465 errgroup.go:93 asm_amd64.s:1700]"
[DBUG] [09-03|07:37:20.612] [removing] removing file                 path=/erigon-data/snapshots/v1.1-041867-041868-transactions.idx.tmp stack="[rw_dir.go:200 recsplit.go:253 block_types.go:339 type.go:68 type.go:274 type.go:396 snapshots.go:1465 errgroup.go:93 asm_amd64.s:1700]"
[DBUG] [09-03|07:37:20.612] [removing] removing file                 path=/erigon-data/temp/erigon-lfp-buf-722831593 stack="[rw_dir.go:200 recsplit.go:258 block_types.go:339 type.go:68 type.go:274 type.go:396 snapshots.go:1465 errgroup.go:93 asm_amd64.s:1700]"
[EROR] [09-03|07:37:20.612] [1/6 OtterSync] Indexing failed          file=v1.1-041400-041500-transactions.seg error="can't open v1.1-041400-041500-bodies.seg for indexing: open /erigon-data/snapshots/v1.1-041400-041500-bodies.seg: no such file or directory"
[EROR] [09-03|07:37:20.612] [1/6 OtterSync] Indexing failed          file=v1.1-041300-041400-headers.seg error="HeadersIdx: can't open v1.1-041300-041400-headers.seg for indexing: open /erigon-data/snapshots/v1.1-041300-041400-headers.seg: no such file or directory"
[EROR] [09-03|07:37:20.612] [1/6 OtterSync] Indexing failed          file=v1.1-041400-041500-headers.seg error="HeadersIdx: can't open v1.1-041400-041500-headers.seg for indexing: open /erigon-data/snapshots/v1.1-041400-041500-headers.seg: no such file or directory"
[EROR] [09-03|07:37:20.612] [1/6 OtterSync] Indexing failed          file=v1.1-041300-041400-bodies.seg error="can't index v1.1-041300-041400-bodies.seg: can't open v1.1-041300-041400-bodies.seg for indexing: open /erigon-data/snapshots/v1.1-041300-041400-bodies.seg: no such file or directory"
[EROR] [09-03|07:37:20.612] [1/6 OtterSync] Indexing failed          file=v1.1-041400-041500-bodies.seg error="can't index v1.1-041400-041500-bodies.seg: can't open v1.1-041400-041500-bodies.seg for indexing: open /erigon-data/snapshots/v1.1-041400-041500-bodies.seg: no such file or directory"
[EROR] [09-03|07:37:20.612] [1/6 OtterSync] Indexing failed          file=v1.1-041300-041400-transactions.seg error="can't open v1.1-041300-041400-bodies.seg for indexing: open /erigon-data/snapshots/v1.1-041300-041400-bodies.seg: no such file or directory"
```

Please, check it.

### PR DESCRIPTION
**Pull request by JkLondon**
closes #16979

### CODE REVIEW

**Review by AskAlexSharov — APPROVED** [review]

**Comment by sudeepdino008** [comment]
once PR is ready, need to scrutinize all places where we might have missed (particularly in snaptype entities)

File: erigon-lib/snaptype/type.go [hunk 1]
```diff
@@ -244,11 +245,29 @@ func (s snapType) FileName(version Version, from uint64, to uint64) string {
 	return SegmentFileName(version, from, to, s.enum)
 }
 
+func (s snapType) FileMask(from uint64, to uint64) string {
+	return SegmentFileMask(from, to, s.enum)
+}
+
 func (s snapType) FileInfo(dir string, from uint64, to uint64) FileInfo {
```
Comment (sudeepdino008) [inline erigon-lib/snaptype/type.go:252]: `FileInfo()` -- it assumes current version, and is used in many places.
Most problematic is in merger.go and snapshots.go#buildMissedAccessors

Comment (sudeepdino008) [reply erigon-lib/snaptype/type.go:252]: check `snapType#HasIndexFiles` -- it generates index file name from seg file name, and i think it assumes that the two have same version.

**Review by sudeepdino008 — CHANGES_REQUESTED** [review]

File: erigon-lib/snaptype/type.go (hunk 1 above)
Comment (JkLondon) [reply erigon-lib/snaptype/type.go:252]: `check snapType#HasIndexFiles -- it generates index file name from seg file name, and i think it assumes that the two have same version.` we've decided to deal with that at 3.2. Now let's assume that they would always have the same ver

Comment (sudeepdino008) [reply erigon-lib/snaptype/type.go:252]: ok ya. If seg and idx are same version...it's fine. Thanks for confirming. 
Just need to fix in merger.go and snapshots.go then

Comment (JkLondon) [reply erigon-lib/snaptype/type.go:252]: snapshots.go calls builder which is changed.

Comment (JkLondon) [reply erigon-lib/snaptype/type.go:252]: merger fixed, would ask @lystopad to test

**Comment by AskAlexSharov** [comment]
```
IndexFile:  filepath.Join(sn.Dir(), snaptype.IdxFileName(sn.Version, sn.From, sn.To, Enums.Events.String())),
```
and probably all usages of `snaptype.IdxFileName`

**Comment by AskAlexSharov** [comment]
current unit-tests failing because of next code:
```
		err = s.openIdx(dir)

		if err != nil {
			if !errors.Is(err, os.ErrNotExist) {
				if optimistic {
					log.Warn("[snapshots] open index", "err", err)
				} else {
					return err
				}
			}
		}
```
this code expecting `errors.Is(err, os.ErrNotExist)` while we returning `fmt.Errorf("[open index] find files by pattern err %w fname %s", err, fName)`. I think we need return `os.ErrNotExist` in all places where we can't find file with given version (or any version). and avoid patterns like `if err != nil || !ok {` 

also I don't see anywhere in code that returned from `FindFilesWithVersionsByPattern` `ok` handled differently from `err`. Maybe `FindFilesWithVersionsByPattern` must return `os.ErrNotExist` instead of `ok`.

**Review by sudeepdino008 — APPROVED** [review]
